### ISSUE TITLE
Port may be garbage, in nyoci_outbound_set_uri()

### ISSUE THREAD

**Issue by snej** [darconeous/libnyoci#2]
Clang's static analyzer reports that the function `nyoci_outbound_set_uri()` uses an uninitialized variable `toport` in some call paths; this seems a legit bug and not a false positive.

```
src/libnyoci/nyoci-outbound.c:501:9: warning: 2nd function call argument is an uninitialized value
                ret = nyoci_plat_set_remote_hostname_and_port(
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

This occurs when `components.host` is non-null but `components.protocol` and `components.port` are null. The flow of control bypasses the three lines where `toport` is assigned but falls through to a line where it's passed to `nyoci_plat_set_remote_hostname_and_port()`.

Xcode doesn't produce a textual version of the detailed flow-control analysis, but here's a screenshot:

<img width="814" alt="screen shot 2018-05-16 at 10 23 04 am" src="https://user-images.githubusercontent.com/43241/40133020-44a9e640-58f3-11e8-8d67-e9c99f7851ee.png">

**Comment by snej** [comment]
I'm guessing the fix is to initialize `toport` to `COAP_DEFAULT_PORT` where it's declared ... ?

**Comment by darconeous** [comment]
Thanks for the fix!
