### ISSUE TITLE
nyoci_outbound_append_content_formatted sets incorrect length

### ISSUE THREAD

**Issue by snej** [darconeous/libnyoci#3]
In `nyoci_outbound_append_content_formatted()`, the variable `fmtlen` is updated but unused:

```c
	fmtlen += self->outbound.content_len;
	ret = nyoci_outbound_set_content_len((coap_size_t)len);
bail:
	va_end(args);
	return ret;
}
```

```
/Couchbase/Embedded/libnyoci/src/libnyoci/nyoci-outbound.c:647:2: warning: Value stored to 'fmtlen' is never read
        fmtlen += self->outbound.content_len;
        ^         ~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I was going to ignore this compiler warning, but then I looked at the code, and it seems like the parameter to `nyoci_outbound_set_content_len()` should be `fmtlen`, not `len` -- the latter is just the space remaining in the packet, while `fmtlen` is the previous `content_len` plus the number of bytes written by `vsnprintf`.

**Comment by darconeous** [comment]
Good catch!
